#!/usr/bin/env zsh

# Confirm we are in Zsh native mode
if [ -z "$ZSH_VERSION" ]; then
  echo "Error: This script must be run with Zsh." >&2
  exit 1
fi

# Emulate pure Zsh (non-POSIX)
emulate -R zsh

# Setup destination
ENV_DIR="$HOME/.config/environment.d"
mkdir -p "$ENV_DIR"

echo ""
echo "==============================================================="
echo "chezmoi: INFO: Regenerating $ENV_DIR/99-env.conf..."

# Step 1: Capture find output into a simple string
find_output="$(find "$HOME/.local/bin" -type d -printf '%p\n')"

# Step 2: Split into an array
IFS=$'\n' read -d '' -r -A path_array <<< "$find_output"

# Step 3: Deduplicate
typeset -U path_array

# Step 4: Validate directories
valid_paths=()
for p in "${path_array[@]}"; do
  [[ -d "$p" ]] && valid_paths+=("$p")
done

# Step 5: Join into a colon-separated PATH string
dynamic_part="${(j.:.)valid_paths}"

# Step 6: Output environment file
{
  echo "# Autogenerated by ChezMoi run_before script"
  echo "PATH=$PATH:$dynamic_part"
} > "$ENV_DIR/99-env.conf"
echo "chezmoi: SUCCESS: Generated $ENV_DIR/99-env.conf."
echo "==============================================================="

