#!/usr/bin/env zsh

# Confirm we are in Zsh native mode
if [ -z "$ZSH_VERSION" ]; then
  echo "Error: This script must be run with Zsh." >&2
  exit 1
fi

# Emulate pure Zsh (non-POSIX)
emulate -R zsh

# Setup destination
ENV_DIR="$HOME/.config/environment.d"
mkdir -p "$ENV_DIR"

echo ""
echo "==============================================================="
echo "chezmoi: INFO: Regenerating $ENV_DIR/99-env.conf..."

# Step 1: Capture find output into an array
path_array=( "${(@f)$(find "$HOME/.local/bin" -type d -print)}" )

# Step 2: Deduplicate the raw list
path_array=( "${(@u)path_array}" )

# Step 3: Validate directories and dedupe on the fly
typeset -U valid_paths
for p in "${path_array[@]}"; do
  [[ -d $p ]] && valid_paths+=( "$p" )
done

# Step 4: Build a fresh, deduplicated PATH
all_paths=( "${(s.:.)PATH}" "${valid_paths[@]}" )
all_paths=( "${(@u)all_paths}" )
new_path="${(j.:.)all_paths}"

# Step 5: Output environment file
{
  echo "# Autogenerated by ChezMoi run_before script"
  echo "PATH=${new_path}"
} > "$ENV_DIR/99-env.conf"

echo "chezmoi: SUCCESS: Generated $ENV_DIR/99-env.conf."
echo "==============================================================="
