swipe:
  3:
    up:
      begin:
        command: "hyprctl dispatch exec 'rofi -show drun'"
    down:
      command: "hyprctl dispatch exec 'pkill rofi'"

  4:
    up:
      end:
        command: "hyprctl dispatch movewindow u"
    left:
      end:
        command: "hyprctl dispatch movewindow l"
    right:
      end:
        command: "hyprctl dispatch movewindow r"
    down:
      end:
        command: "hyprctl dispatch movewindow d"
pinch:
  3:
    in:
      end:
        command: "hyprctl dispatch killactive"
        #    out:
        #      end:
        #        command: "hyprctl dispatch fullscreen 1"
hold:
  4:
    begin:
        command: "hyprctl dispatch fullscreen 1"
        #  3:
        #    end:
        #      command: "hyprctl dispatch exec kitty"

threshold:
  swipe: 0.5   # Sensitivity threshold
interval:
  swipe: 0.8   # Swipe recognition time

