#!/bin/bash
if [ "$(hostnamectl hostname)" = "waynemini" ]
then
    task -WAITING and -PARENT and \(+OVERDUE or +DUETODAY\) _ids | {
	while read -r i
	do
	    echo "[0] - $(task _get "$i.description" 2> /dev/null)"
	done } | sort --unique > ~/.local/share/calcurse/todo
fi
