#!/bin/bash
if [ "$(hostname)" == 'waynepc' ]
then
tasks=$(grep "task:" ~/.calcurse/apts)
IFS=$'\n'
for n in $tasks
do
    task=${n/'[1] task: '/}
    due=$(echo "$task" | awk 'BEGIN{FS=" "} {print $1}')
    task=${task#"$due "}
    due=$(date -d "$due" +%_m-%_d-%y)
    task add "$task" due:"$due"
    sed -i /"task: $task"/d ~/.calcurse/apts
done
fi
